# Based on https://github.com/huggingface/api-inference-community/blob/main/docker_images/diffusers/Dockerfile

FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu22.04

# Add any system dependency here
# RUN apt-get update -y && apt-get install libXXX -y

ENV DEBIAN_FRONTEND=noninteractive

# Install prerequisites
RUN apt-get update && \
  apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
  libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
  xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git \
  ffmpeg supervisor

# Install pyenv
RUN curl https://pyenv.run | bash

# Set environment variables for pyenv
ENV PYENV_ROOT=/root/.pyenv
ENV PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

# Install your desired Python version
ARG PYTHON_VERSION=3.11
RUN pyenv install $PYTHON_VERSION && \
  pyenv global $PYTHON_VERSION && \
  pyenv rehash

# Install pyenv-virtualenv
RUN git clone https://github.com/pyenv/pyenv-virtualenv.git $(PYENV_ROOT)/plugins/pyenv-virtualenv
#activate pyenv and pyenv-virtualenv
RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc && \
    echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
WORKDIR /app
# create a virtualenv for comfyui
ENV PYTHONDONTWRITEBYTECODE=1
RUN pyenv virtualenv $PYTHON_VERSION comfyui-base --system-site-packages

RUN eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv activate comfyui-base && pip install --no-cache-dir --upgrade pip setuptools wheel && \
  pip install --no-cache-dir torch==2.7 torchvision torchaudio transformers diffusers numpy>=1.26.4 accelerate tqdm && \
  pip install git+https://github.com/huggingface/diffusers && \
  pip install comfy-cli fastapi uvicorn httpx nvidia-ml-py==12.560.30 pynvml==12.0.0 prometheus_client>=0.21.1 GitPython python-multipart

RUN mkdir /app/workspace

RUN git clone https://github.com/comfyanonymous/ComfyUI.git /app/workspace
RUN git clone https://github.com/ltdrdata/ComfyUI-Manager /app/workspace/custom_nodes/ComfyUI-Manager && \
    git clone https://github.com/rgthree/rgthree-comfy.git /app/workspace/custom_nodes/rgthree-comfy && \
    git clone https://github.com/city96/ComfyUI-GGUF.git /app/workspace/custom_nodes/ComfyUI-GGUF && \
    git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git /app/workspace/custom_nodes/ComfyUI-VideoHelperSuite

RUN eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv activate comfyui-base && pip install -r /app/workspace/requirements.txt
RUN eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv activate comfyui-base && pip install -r /app/workspace/custom_nodes/ComfyUI-Manager/requirements.txt
RUN eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv activate comfyui-base && pip install -r /app/workspace/custom_nodes/rgthree-comfy/requirements.txt
RUN eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv activate comfyui-base && pip install -r /app/workspace/custom_nodes/ComfyUI-GGUF/requirements.txt
RUN eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv activate comfyui-base && pip install -r /app/workspace/custom_nodes/ComfyUI-VideoHelperSuite/requirements.txt
ENV PATH="/root/.pyenv/versions/comfyui-base/bin:$PATH"

ENV PYTHONPATH=$PYENV_ROOT/versions/comfyui-base

COPY ./batch.sh .
COPY ./batch_pipelines_refresh.py .
COPY ./batch.supervisord.conf /etc/supervisor/conf.d/batch.conf
ENV PATH="/app/venv/bin:$PATH"
RUN mkdir -p /var/log/comfy

# Most DL models are quite large in terms of memory, using workers is a HUGE
# slowdown because of the fork and GIL with python.
# Using multiple pods seems like a better default strategy.
# Feel free to override if it does not make sense for your library.
ARG max_workers=1
ENV MAX_WORKERS=$max_workers
ENV HUGGINGFACE_HUB_CACHE=/models
ENV DIFFUSERS_CACHE=/models
ENV MODEL_DIR=/models

ARG VERSION="undefined"
ENV VERSION=${VERSION}

#env variable used to load venv for pipelines
ENV PIPELINE_VENV=comfyui

RUN git config --global --add safe.directory /app/workspace/custom_nodes

COPY app/ /app/app

CMD ["/usr/bin/supervisord"]


